inherit_mode:
  merge:
    - Exclude

require: rubocop-rails

AllCops:
  Exclude:
    - 'db/*schema.rb'
    - 'db/migrate/*.rb'
    - 'lib/scratch/*.rb'

#################### Gemspec###########################

Gemspec/DateAssignment:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

#################### Layout ###########################

Layout/AccessModifierIndentation:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ClassStructure:
  Enabled: true

Layout/EndAlignment:
  AutoCorrect: true

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: false

#################### Lint ##################################
### Warnings

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/InheritException:
  EnforcedStyle: standard_error

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
  AllowComments: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 25
  CountAsOne: []
  IgnoredMethods:
    # By default, exclude the `#refine` method, as it tends to have larger
    # associated blocks.
    - refine

Metrics/BlockNesting:
  Description: 'Avoid excessive block nesting.'
  StyleGuide: '#three-is-the-number-thou-shalt-count'
  Enabled: true
  CountBlocks: false
  Max: 3

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Description: >-
                 A complexity metric that is strongly correlated to the number
                 of test cases needed to validate a method.
  Enabled: false
  IgnoredMethods: []
  Max: 7

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 10

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: false
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Description: >-
                 A complexity metric geared towards measuring complexity for a
                 human reader.
  Enabled: true
  IgnoredMethods: []
  Max: 8

#################### Naming ##############################

Naming/BlockForwarding:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - ad
    - as
    - by
    - e
    - i
    - id
    - io
    - of
    - to

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - capture3
    - iso8601
    - rfc1123_date
    - rfc822
    - rfc2822
    - rfc3339
    - s3
    - switched_to_v1
    - switched_to_v2
    - !ruby/regexp /\bmd5\b/
    - !ruby/regexp /\bs3\b/
    - !ruby/regexp /\bv\d+\b/

#################### Security #############################

Security/IoMethods:
  Enabled: true

#################### Style ###############################

# We don't do either much, but I've heard arguments for both sides.
Style/AccessorGrouping:
  Enabled: true

# TODO: Pick one!
Style/Alias:
  Enabled: false
  EnforcedStyle: prefer_alias

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

# e.g. File.open { ... } which auto-closes instead of just f = File.open
Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

# TODO: Update in files and then enable
Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: nested

Style/CollectionCompact:
  Enabled: true

# Align with the style guide.
Style/CollectionMethods:
  Enabled: false

Style/CombinableLoops:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: compact

Style/EndlessMethod:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/FormatString:
  Enabled: true
  EnforcedStyle: format

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/IpAddresses:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/MapToHash:
  Enabled: true

# TODO: Divided on this one.  Disabled until we reach a majority, if not a consensus.
Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/ModuleFunction:
  Enabled: false
  EnforcedStyle: module_function
  SupportedStyles:
    - module_function
    - extend_self
    - forbidden

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/QuotedSymbols:
  Enabled: false

Style/RedundantArgument:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: implicit

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Style/SelectByRegexp:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringHashKeys:
  Enabled: false

# omg
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SwapValues:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

#################### Rails ###############################

Rails:
  Exclude:
    - 'lib/scratch/*'

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ActiveRecordOverride:
  Enabled: false

Rails/ActiveSupportAliases:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - 'db/**/*'

Rails/BulkChangeTable:
  Enabled: false
  Database: postgresql

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

# lol
Rails/DefaultScope:
  Enabled: false

Rails/Delegate:
  Enabled: true
  EnforceForPrefixed: true

Rails/DurationArithmetic:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: true

Rails/ExpandedDateRange:
  Enabled: true

# Actually semantically different; find_by doesn't enforce an ordering, whereas first does
Rails/FindBy:
  Enabled: false

Rails/FindById:
  Enabled: true

# Meh.  Just means more models, sometimes
Rails/HasAndBelongsToMany:
  Enabled: false

# Should probably enable...
Rails/HelperInstanceVariable:
  Enabled: false
  Include:
    - app/helpers/**/*.rb

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: true
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
  Exclude:
    - lib/scratch/*.rb

# :eye-roll:
# Should probably enable.  There are places where we will likely need to explicitly disable, though
Rails/OutputSafety:
  Description: 'The use of `html_safe` or `raw` may be a security risk.'
  Enabled: false

# When an association is eagerly loaded, pluck may issue another query
Rails/Pluck:
  Enabled: false

# Now that arrays respond to :pluck, we occasionally use it on things that don't respond to :ids
Rails/PluckId:
  Enabled: false

# Not always!
Rails/PluckInWhere:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/SaveBang:
  Enabled: true
  AllowImplicitReturn: true
  AllowedReceivers: ['Aws.config', 'cipher', 'decipher', 'ReportHighlightsEmailsController', 'Tempfile']

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  ForbiddenMethods:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - insert
    - insert!
    - insert_all
    - insert_all!
    - toggle!
    - touch
    - touch_all
    - update_all
    - update_attribute
    - update_column
    - update_columns
    - update_counters
    - upsert
    - upsert_all
  AllowedMethods: []
  Exclude:
    - db/migrate/*.rb
    - spec/**/*_spec.rb

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

# Accept `redirect_to(...) and return` and similar cases.
Style/AndOr:
  EnforcedStyle: conditionals
